import { Layout } from "@/components/Layout/Layout";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/contexts/theme";
import { DeviceProvider } from "@/contexts/device";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <DeviceProvider>
            <Layout>{children}</Layout>
          </DeviceProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}